name: Deploy Flask App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 and Run Flask
        uses: appleboy/ssh-action@master
        with:
          host: 13.233.151.233
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/flask-ci-cd-demo
            git pull origin main

            # Stop any existing Flask process
            pkill -f "python3 app.py" || true

            # Start Flask in the background
            /home/ubuntu/flask-ci-cd-demo/flaskenv/bin/python3 app.py > flask.log 2>&1 &
