name: Deploy Flask App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 and restart Flask
        uses: appleboy/ssh-action@master
        with:
          host: 13.233.151.233
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/flask-ci-cd-demo
            git pull origin main
            sudo systemctl restart flaskapp
